name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  # ðŸ”§ Define Strategy Matrix
  _define:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ toJson(matrix) }}
    strategy:
      matrix: &go-matrix
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.24", "1.25"]
        include:
          - os: ubuntu-latest
            go-build: ~/.cache/go-build
          - os: macos-latest
            go-build: ~/Library/Caches/go-build
    steps:
      - run: echo "Matrix defined"

  # ðŸ§¹ Check Job
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1"
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.1.6
          args: --verbose
      - name: vet
        run: go vet ./...

  # ðŸ—ï¸ Build Job
  build:
    needs: [_define, check]
    strategy:
      matrix: *go-matrix
    name: Build (${{ matrix.os }} Go ${{ matrix.go }})
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - uses: actions/cache@v5
        with:
          path: |
            ${{ matrix.go-build }}
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-

      - name: Build Project
        run: go build ./...

  # ðŸ§ª Test Job
  test:
    needs: [_define, build]
    strategy:
      matrix: *go-matrix
    name: Test (${{ matrix.os }} Go ${{ matrix.go }})
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      TESTTAGS: "-tags nomsgpack --ldflags='-checklinkname=0' -tags sonic -tags go_json -race"
      GOPROXY: https://proxy.golang.org

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - uses: actions/cache@v5
        with:
          path: |
            ${{ matrix.go-build }}
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-

      - name: Run Tests
        run: go test -v --cover ./... -coverprofile=coverage.out -covermode=count -json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: ${{ matrix.os }},go-${{ matrix.go }}

  # ðŸ‘¹ Gremlins Job
  gremlins:
    needs: [build]
    name: Unleash Gremlins
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-go@v6
        with:
          go-version: 1.24
          cache: false

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.24-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.24-

      - name: Install
        run: |
          go install github.com/go-gremlins/gremlins/cmd/gremlins@v0.5.0
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Unleash
        run: gremlins unleash --config=.gremlins.yaml --output=gremlins.json
